name: Home Assistant Nightly Beta Tests

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:      
  beta-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install deps
        run: pnpm install
      - name: E2E Tests
        run: TAG=beta pnpm test:ci
      - name: Create coverage
        run: pnpm coverage:report
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-report
          path: |
            playwright-report/
            coverage/
          retention-days: 30